### ISSUE TITLE
Subcribe to newsletter within checkout process

### ISSUE THREAD

**Issue by convict666** [cubecart/v5.2.14#129]
Standard registration form includes this option but checkout

**Comment by havenswift-hosting** [comment]
Any chance of getting this issue / enhancement added ASAP please ?  It doesnt seem that it would be a major coding change but would have a big impact on the number of signups that stores would get to their newsletters

**Comment by abrookbanks** [comment]
This has been added to v6. I won't be adding it to v5 I'm afraid. Sorry.

**Comment by havenswift-hosting** [comment]
No problem at all adding it only to V6 - I completely agree with that policy as you know !  This issue was still under the old 5.2.14 list.

Did this require any skin changes and if so do you have details ?  V6 users using old V5 skins may want to make the same change so that it will work for them as well

**Comment by abrookbanks** [comment]
Ah right. I coped soe across but you can't delete them. I'll get some closed up...
